#source 'https://github.com/gmunhoz/CollieGallery.git'

project 'CollieGallery'
inhibit_all_warnings!
use_frameworks!

target 'CollieGallery_Example' do
    pod 'CollieGallery', :path => '../'
end

target 'CollieGallery_Tests' do
    pod 'CollieGallery', :path => '../'
    pod 'Quick', '0.10.0’
    pod 'Nimble', '5.0.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
      config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.10'
    end
  end
end
