source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CollieGallery_Example', :exclusive => true do
  pod 'CollieGallery', :path => '../'
end

target 'CollieGallery_Tests', :exclusive => true do
  pod 'CollieGallery', :path => '../'

  pod 'Quick', '~> 0.8.0'
  pod 'Nimble', '4.1.0'
end
